{
  "formatVersion": "1.1",
  "component": {
    "group": "com.engineer.third",
    "module": "thirdlib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.weijiaxing",
          "module": "LogcatViewer",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "blurry",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.squareup.radiography",
          "module": "radiography",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "20030203.000550"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "thirdlib-1.0.0.aar",
          "url": "thirdlib-1.0.0.aar",
          "size": 392106,
          "sha512": "d6a8830c00821d874da4831c24c267857eff61b199fd676fb95f0b5538548206883662dbfb2349a3361f517f90f41295423c6986bfbd5b3e65c8f6386e5a4d95",
          "sha256": "5bd2f07e37b9ef6edda164697c030fa8ece197b9ab4e37604ea6e242fa72f842",
          "sha1": "8f47723c1e0a1bdedd4cceb2e29497e1c3d2adc9",
          "md5": "b25b95e8ddd67f77e1f0ce9cc776bfc9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.weijiaxing",
          "module": "LogcatViewer",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "blurry",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.squareup.radiography",
          "module": "radiography",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "20030203.000550"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "thirdlib-1.0.0.aar",
          "url": "thirdlib-1.0.0.aar",
          "size": 392106,
          "sha512": "d6a8830c00821d874da4831c24c267857eff61b199fd676fb95f0b5538548206883662dbfb2349a3361f517f90f41295423c6986bfbd5b3e65c8f6386e5a4d95",
          "sha256": "5bd2f07e37b9ef6edda164697c030fa8ece197b9ab4e37604ea6e242fa72f842",
          "sha1": "8f47723c1e0a1bdedd4cceb2e29497e1c3d2adc9",
          "md5": "b25b95e8ddd67f77e1f0ce9cc776bfc9"
        }
      ]
    }
  ]
}
