{
  "formatVersion": "1.1",
  "component": {
    "group": "com.engineer.third",
    "module": "thirdlib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "thirdlib-1.0.0.aar",
          "url": "thirdlib-1.0.0.aar",
          "size": 526406,
          "sha512": "1b5691a19f19d36b9cde535a5ba3de4065fa57bb8e1b78d00a0ccf328040b481d730bf97251ff5235331916a5bfa804703871f033197004c77dc57bc71d213cc",
          "sha256": "00eb7d389790faccceb2958825e7da6be64e26b0f2d92df37716d00045e17eb4",
          "sha1": "794f9f2af5dac6b5916655043d9cb270fdec57e9",
          "md5": "e3a64bf02eb401c35254f83238c388a6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "thirdlib-1.0.0.aar",
          "url": "thirdlib-1.0.0.aar",
          "size": 526406,
          "sha512": "1b5691a19f19d36b9cde535a5ba3de4065fa57bb8e1b78d00a0ccf328040b481d730bf97251ff5235331916a5bfa804703871f033197004c77dc57bc71d213cc",
          "sha256": "00eb7d389790faccceb2958825e7da6be64e26b0f2d92df37716d00045e17eb4",
          "sha1": "794f9f2af5dac6b5916655043d9cb270fdec57e9",
          "md5": "e3a64bf02eb401c35254f83238c388a6"
        }
      ]
    }
  ]
}
