{
  "formatVersion": "1.1",
  "component": {
    "group": "com.engineer.third",
    "module": "base_api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.weijiaxing",
          "module": "LogcatViewer",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "blurry",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.squareup.radiography",
          "module": "radiography",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "base_api-1.0.0.aar",
          "url": "base_api-1.0.0.aar",
          "size": 392104,
          "sha512": "1b8ddff31c155d47ebd92d796b7112211a98ac86a47430e566ebec84e0b32bd4d79e222396c763f73447925c6731b7baef5c7eff1e552e263c6f4e421ca79410",
          "sha256": "207c111627746680a46e14bd5a383bf177943ae6ef5f2e385de6cba37228b5c4",
          "sha1": "1d28a0589b5e9231ef234379301a6df3f6eed019",
          "md5": "efeae9c3a3bccadce829d1241a769702"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.weijiaxing",
          "module": "LogcatViewer",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "blurry",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.squareup.radiography",
          "module": "radiography",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "base_api-1.0.0.aar",
          "url": "base_api-1.0.0.aar",
          "size": 392104,
          "sha512": "1b8ddff31c155d47ebd92d796b7112211a98ac86a47430e566ebec84e0b32bd4d79e222396c763f73447925c6731b7baef5c7eff1e552e263c6f4e421ca79410",
          "sha256": "207c111627746680a46e14bd5a383bf177943ae6ef5f2e385de6cba37228b5c4",
          "sha1": "1d28a0589b5e9231ef234379301a6df3f6eed019",
          "md5": "efeae9c3a3bccadce829d1241a769702"
        }
      ]
    }
  ]
}
