
dependencies {
    implementation libs.androidx.navigation.ui.ktx
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.hilt.android
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation project(path: ':deps:filter')
    implementation libs.androidx.activity
    ksp libs.hilt.android.compiler
}