dependencies {
    implementation libs.google.gson
    implementation libs.squareup.retrofit2.converter.gson
    implementation libs.squareup.retrofit2.retrofit
    implementation libs.squareup.retrofit2.adapter.rxjava2

    implementation libs.reactivex.rxjava2.rxjava
    implementation libs.reactivex.rxjava2.rxandroid
}
