dependencies {
    def arch_version = "2.1.0"

    // ViewModel
    implementation libs.androidx.lifecycle.viewmodel.ktx
    // LiveData
    implementation libs.androidx.lifecycle.livedata.ktx


    // deprecated
    // implementation "androidx.lifecycle:lifecycle-extensions:$lifecycle_version"

    // Lifecycles only (without ViewModel or LiveData)
    implementation libs.androidx.lifecycle.runtime.ktx

    // Saved state module for ViewModel
    implementation libs.androidx.lifecycle.viewmodel.savedstate

    // Annotation processor
//    ksp "androidx.lifecycle:lifecycle-compiler:$lifecycle_version"
    // alternately - if using Java8, use the following instead of lifecycle-compiler
    implementation libs.androidx.lifecycle.common.java8

    // optional - helpers for implementing LifecycleOwner in a Service
    implementation libs.androidx.lifecycle.service

    // optional - ProcessLifecycleOwner provides a lifecycle for the whole application process
    implementation libs.androidx.lifecycle.process

//    // optional - ReactiveStreams support for LiveData
//    implementation "androidx.lifecycle:lifecycle-reactivestreams-ktx:$lifecycle_version"
//
//    // optional - Test helpers for LiveData
//    testImplementation "androidx.arch.core:core-testing:$arch_version"


    // Room for database
    implementation libs.androidx.room.ktx
    ksp libs.androidx.room.compiler

    implementation libs.androidx.work.runtime.ktx
}
